<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251221085044 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE rule_package_processing_job (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, source_updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, type INT NOT NULL, mimetype VARCHAR(255) DEFAULT NULL, processed_import_data TEXT NOT NULL, import_tasks INT NOT NULL, processed_import_tasks INT NOT NULL, processed_cleanup_data TEXT NOT NULL, cleanup_tasks INT NOT NULL, processed_cleanup_tasks INT NOT NULL, rule_package_id INT DEFAULT NULL, project_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4E75826FCFFD2724 ON rule_package_processing_job (rule_package_id)');
        $this->addSql('CREATE INDEX IDX_4E75826F166D1F9C ON rule_package_processing_job (project_id)');
        $this->addSql('ALTER TABLE rule_package_processing_job ADD CONSTRAINT FK_4E75826FCFFD2724 FOREIGN KEY (rule_package_id) REFERENCES rule_package (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE rule_package_processing_job ADD CONSTRAINT FK_4E75826F166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE rule_package_cache ALTER refreshed_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE rule_package_cache ALTER refreshed_at DROP NOT NULL');
        $this->addSql('ALTER TABLE rule_package_cache ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE rule_package_cache ALTER updated_at DROP NOT NULL');
        $this->addSql('ALTER TABLE rule_package_rule_cache ADD number_of_items INT DEFAULT NULL');
        $this->addSql('ALTER TABLE rule_package_rule_cache ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE rule_package_rule_item_cache ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('CREATE INDEX rpric_rprc_project_idx ON rule_package_rule_item_cache (project_id, rule_package_rule_cache_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE rule_package_processing_job DROP CONSTRAINT FK_4E75826FCFFD2724');
        $this->addSql('ALTER TABLE rule_package_processing_job DROP CONSTRAINT FK_4E75826F166D1F9C');
        $this->addSql('DROP TABLE rule_package_processing_job');
        $this->addSql('ALTER TABLE rule_package_rule_cache DROP number_of_items');
        $this->addSql('ALTER TABLE rule_package_rule_cache DROP updated_at');
        $this->addSql('DROP INDEX rpric_rprc_project_idx');
        $this->addSql('ALTER TABLE rule_package_rule_item_cache DROP updated_at');
        $this->addSql('ALTER TABLE rule_package_cache ALTER refreshed_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE rule_package_cache ALTER refreshed_at SET NOT NULL');
        $this->addSql('ALTER TABLE rule_package_cache ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE rule_package_cache ALTER updated_at SET NOT NULL');
    }
}
