<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250410171419 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE cleanup_statistic (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cleanup_executor INT NOT NULL, number_of_stored_submit_tokens INT NOT NULL, number_of_deleted_submit_tokens INT NOT NULL, number_of_stored_submissions INT NOT NULL, number_of_deleted_submissions INT NOT NULL, execution_time DOUBLE PRECISION NOT NULL, cleanup_status INT NOT NULL, PRIMARY KEY(id))
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            DROP TABLE cleanup_statistic
        SQL);
    }
}
