<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260117181852 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, translation_key INT NOT NULL, locale VARCHAR(8) NOT NULL, text TEXT NOT NULL, project_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B469456F166D1F9C ON translation (project_id)');
        $this->addSql('CREATE INDEX t_ltk_idx ON translation (project_id, translation_key, locale)');
        $this->addSql('ALTER TABLE translation ADD CONSTRAINT FK_B469456F166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE translation DROP CONSTRAINT FK_B469456F166D1F9C');
        $this->addSql('DROP TABLE translation');
    }
}
