services:
  db:
    # We recommend the mariadb image
    image: mariadb:11.4
    # If you want to use MySQL, uncomment the following line (and comment the one above)
    #image: mysql:8.0.37
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mosparo_root_pw
      - MYSQL_DATABASE=mosparo
      - MYSQL_USER=mosparo
      - MYSQL_PASSWORD=mosparo_password
    expose:
      - 3306
      - 33060
  mosparo_web:
    image: mosparo/mosparo-unprivileged:latest
    ports:
      - 8080:8080
    restart: always
    environment:
      - MOSPARO_RUN_NGINX=1
      - MOSPARO_RUN_PHP_FPM=1
      #- MOSPARO_CLEANUP_GRACE_PERIOD_ENABLED=1
    volumes:
      - mosparo_config:/mosparo-config
      - mosparo_public_resources:/mosparo/public/resources
      - mosparo_var:/mosparo/var
volumes:
  db_data:
  mosparo_config:
  mosparo_public_resources:
  mosparo_var: