name: Automated testing
on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: [ "8.1", "8.2", "8.3", "8.4" ] # 8.5 is disabled because the dependencies are not yet ready for 8.5

    steps:
      - uses: actions/checkout@v6

      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-version }}
          php_extensions: gd intl pdo_mysql pdo_sqlite zip sodium
          memory_limit: 256M

      - uses: php-actions/phpunit@v4
        with:
          php_version: ${{ matrix.php-version }}
          php_extensions: gd intl pdo_mysql pdo_sqlite zip sodium
          memory_limit: 256M
          configuration: phpunit.xml.dist