name: Build mosparo Docker images

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [standard, unprivileged]
    env:
      tagSuffix: ${{ matrix.type == 'unprivileged' && '-unprivileged' || '' }}
      mosparoChannel: ${{ contains(github.event.release.tag_name, '-beta.') && 'beta' || 'stable' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Define Docker meta
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: "mosparo/mosparo${{ env.tagSuffix }}"
          tags: |
            type=raw,value=${{ github.event.release.tag_name }}
            type=raw,value=latest,enable=${{ !contains(github.event.release.tag_name, '-beta.') }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "mosparo/cloud-builder"
          install: true

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm/v7,linux/386,linux/amd64,linux/arm/v5,linux/arm64/v8
          context: "docker/${{ matrix.type }}/"
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            MOSPARO_VERSION=${{ github.event.release.tag_name }}
            MOSPARO_CHANNEL=${{ env.mosparoChannel }}
          outputs: 'type=registry'